spring:
  application:
    name: online-shop
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/online_shop_db}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  allowed-routes:
    - "/users/api/v1/register"
    - "/users/api/v1/login"
    - "/products/api/v1/all"
    - "/"
    - "/swagger-ui/**"
    - "/swagger-resources/**"
    - "/v3/api-docs/**"

cross-origin:
  allowed-origin: "http://localhost:3000"
